dist: bionic
language: java
jdk:
  - oraclejdk8

env:
  - BUILD_TIMESTAMP=$(date +%Y%m%d%H%M) BUILD_REVISION=g${TRAVIS_COMMIT:0:8}

cache:
  directories:
    - $HOME/.gradle

before_install:
  - pyenv global 3.6
install:
  - pip install requests
script:
  - ./bin/test.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/publish.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./bin/dqs-sync.sh
    on:
      all_branches: true
after_failure:
  - reports-publisher

after_success:
  - reports-publisher

notifications:
  slack: adevinta:CnDdVjsExnkqmUodfX2zWQpR
  if: branch = master
  on_success: change
  on_failure: always




